Port over installation instructions
gabro/scalafmt pull request #2
Opened 2018-07-24 18:09 UTC by mads-hartmann

There are a few caveats:

I used @VERSION@ all the places where 1.5.1 was mentioned on the site.
On my branch that's currently 1.6.0-RC1-14-b09fd59a. I don't know
if we need to distinguish between the current version and the stable
version

The --help section is a bit funny as it's shown as a REPL session now
and therefore some of the text is truncated. I haven't used tut before,
is there a better way to do this?

I haven't ported the intellij section over as I believe it's now built
in?

2018-07-25 13:53 UTC, gabro requested changes
Great! I've tried to answer your points inline

2018-07-25 13:53 UTC, gabro commented on docs/installation.md
> +coursier bootstrap com.geirsson:scalafmt-cli_2.12:@VERSION@ \
Right, it would probably make sense to have a `STABLE_VERSION` of some sort here. It can be computed in sbt and injected in the build.

2018-07-25 13:53 UTC, gabro commented on docs/installation.md
> +```tut
you should be able to use `tut:passthrough` to avoid the repl output.

2018-07-26 06:27 UTC, mads-hartmann commented
I ported over the IntelliJ instructions - we can always change them later. I wish docusaurus has support for [Admonition](https://squidfunk.github.io/mkdocs-material/extensions/admonition/) but it doesn't look like it can be activated so I had to use plain HTML to do the sidenote.

2018-07-27 15:25 UTC, mads-hartmann commented
@gabro This should be ready to merge :)

2018-07-30 07:38 UTC, mads-hartmann commented
@gabro Solved the conflict through a rebase and made a few small changes in a6bd183. Do you know if it's possible to enable markdown processing in HTML block so we don't have to use `<a>` tags? Or preferable if docusaurus has support for [Admonition](https://squidfunk.github.io/mkdocs-material/extensions/admonition/)? If neither is possible then I'm also happy getting this merged as is :)

2018-07-31 11:13 UTC, gabro commented
@mads-hartmann there's no support for Admonition and I haven't found any option for enabling parsing markdown inside html blocks. Merging for now, we'll see whether it can be improved later.

2018-07-31 11:13 UTC, merged